//! Toolkit-loaded content assembled and validated without a graphics context.

pub mod combat;
pub mod construction;
pub mod economy;
pub mod progression;
pub mod rules;
mod setup_validation;
mod validation;
pub mod world;
mod world_validation;

use serde::Deserialize;
use std::collections::BTreeMap;

#[derive(Debug, Clone, Deserialize)]
pub struct GeographyLabel {
    pub name: String,
    pub position: [f32; 2],
    pub size: f32,
}

#[derive(Debug, Clone)]
pub struct GameData {
    pub construction: construction::ConstructionRules,
    pub progression: progression::ProgressionRules,
    pub history: progression::HistoryRules,
    pub troops: combat::Troops,
    pub combat: combat::CombatRules,
    pub presentation: PresentationData,
    pub economy: economy::Economy,
    pub rules: rules::CampaignRules,
    pub scenario: world::Scenario,
}

impl GameData {
    pub fn load() -> Result<Self, String> {
        let data = Self {
            construction: macroquad_toolkit::include_json!(
                "../assets/data/construction_rules.json"
            )?,
            progression: macroquad_toolkit::include_json!("../assets/data/progression.json")?,
            history: macroquad_toolkit::include_json!("../assets/data/history_rules.json")?,
            troops: macroquad_toolkit::include_json!("../assets/data/troops.json")?,
            combat: macroquad_toolkit::include_json!("../assets/data/combat_rules.json")?,
            presentation: macroquad_toolkit::include_json!("../assets/data/game_config.json")?,
            economy: macroquad_toolkit::include_json!("../assets/data/economy.json")?,
            rules: macroquad_toolkit::include_json!("../assets/data/campaign_rules.json")?,
            scenario: macroquad_toolkit::include_json!("../assets/data/scenarios/rosemarch.json")?,
        };
        data.validate()?;
        Ok(data)
    }

    pub fn validate(&self) -> Result<(), String> {
        self.construction.validate()?;
        self.progression.validate()?;
        self.history.validate()?;
        self.troops.validate()?;
        self.combat.validate()?;
        self.presentation.validate()?;
        self.economy.validate()?;
        self.rules.validate()?;
        self.scenario.validate(&self.rules, &self.economy)
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct PresentationData {
    pub game_id: String,
    pub title: String,
    pub subtitle: String,
    pub edition: String,
    pub map_path: String,
    pub font_path: String,
    pub body_font_path: String,
    pub start_year: u32,
    pub seasons: Vec<String>,
    pub geography: Vec<GeographyLabel>,
    pub text: BTreeMap<String, String>,
}

const REQUIRED_TEXT: &[&str] = &[
    "settlement",
    "settlement_manage",
    "settlement_overview",
    "settlement_build",
    "settlement_roads",
    "settlement_focus",
    "settlement_population",
    "settlement_damage",
    "settlement_fortification",
    "settlement_facilities",
    "none",
    "construction_outpost",
    "construction_road",
    "construction_road_repair",
    "construction_fort",
    "facility_training",
    "facility_stable",
    "facility_infirmary",
    "facility_workshop",
    "facility_temple",
    "facility_damaged",
    "habitation_unsettled",
    "habitation_camp",
    "habitation_outpost",
    "habitation_hamlet",
    "habitation_village",
    "habitation_town",
    "habitation_city",
    "habitation_major_city",
    "focus_growth",
    "focus_fortification",
    "focus_training",
    "focus_gold",
    "focus_wood",
    "focus_stone",
    "focus_confirm",
    "focus_current_effect",
    "focus_success",
    "construction_active",
    "construction_paused",
    "construction_completed",
    "construction_cancelled",
    "construction_orders",
    "construction_no_orders",
    "construction_no_routes",
    "construction_review",
    "construction_steps",
    "construction_timing",
    "construction_prepaid",
    "construction_progress",
    "construction_details",
    "construction_choose_builder",
    "construction_builder",
    "construction_no_builder",
    "construction_builder_help",
    "construction_no_builders",
    "construction_builder_placement",
    "construction_builder_remain",
    "construction_assign",
    "construction_confirm",
    "construction_replace_builder",
    "construction_cancel",
    "construction_confirm_cancel",
    "construction_cancel_help",
    "construction_refund",
    "construction_success",
    "construction_cancel_success",
    "construction_builder_success",
    "construction_outpost_effect",
    "construction_road_effect",
    "construction_repair_effect",
    "construction_fort_effect",
    "facility_stable_effect",
    "facility_infirmary_effect",
    "facility_workshop_effect",
    "facility_training_effect",
    "facility_temple_effect",
    "help_construction",
    "help_builder",
    "help_construction_refund",
    "move_observed_hostile",
    "evidence_retreating_enemy_victory",
    "battle_veterancy_factor",
    "class_medic",
    "records",
    "records_help",
    "history",
    "history_overview",
    "history_events",
    "history_filters",
    "history_search",
    "history_open",
    "history_report",
    "history_places",
    "history_service",
    "army_history",
    "formation_service",
    "history_retention_help",
    "history_last_known_help",
    "history_empty",
    "history_own_person",
    "last_encountered",
    "history_filter_help",
    "history_all_events",
    "history_battles",
    "history_movement",
    "history_veterancy",
    "history_from",
    "history_to",
    "history_any_season",
    "history_reset_filters",
    "history_apply_filters",
    "history_search_help",
    "history_report_expired",
    "history_battle",
    "history_recruited",
    "history_disbanded",
    "history_moved",
    "history_formation_transferred",
    "history_person_transferred",
    "history_people_recorded",
    "history_armies_recorded",
    "history_current_site",
    "history_observed_role",
    "history_observed_condition",
    "history_observed_army",
    "history_recorded_details",
    "history_unknown_person",
    "history_no_hidden_facts",
    "history_age",
    "history_service_start",
    "history_personal_service",
    "history_no_inherited_deeds",
    "service_xp",
    "service_highest_tier",
    "service_combat_factor",
    "service_earning",
    "service_round_cap",
    "service_preserved",
    "service_recovery_help",
    "service_recent",
    "service_encounters",
    "service_recorded_occurrences",
    "service_encountered",
    "service_no_evidence",
    "service_no_evidence_help",
    "evidence_battle",
    "evidence_meaningful",
    "evidence_victory",
    "evidence_defeat",
    "evidence_outnumbered",
    "evidence_defended_anchor",
    "evidence_captured_anchor",
    "evidence_retreated",
    "evidence_treated",
    "evidence_commander_wounded",
    "evidence_assumed_command",
    "evidence_commanded_victory",
    "tier_ordinary",
    "tier_seasoned",
    "tier_veteran",
    "hostile_presence",
    "help_service",
    "help_history",
    "help_knowledge",
    "new_game",
    "continue",
    "no_save",
    "settings",
    "help",
    "credits",
    "quit",
    "menu",
    "resume",
    "save",
    "load",
    "main_menu",
    "back",
    "close",
    "end_turn",
    "world_map",
    "turn",
    "year",
    "phase",
    "zoom_in",
    "zoom_out",
    "reset_view",
    "labels",
    "contrast",
    "on",
    "off",
    "standard",
    "high",
    "fullscreen",
    "help_title",
    "help_army",
    "help_recruit",
    "help_slots",
    "help_economy",
    "help_disband",
    "help_move",
    "help_route",
    "help_transfer",
    "help_spent",
    "help_recovery",
    "help_transfer_phase",
    "move_group",
    "move_group_help",
    "move_armies",
    "move_army",
    "selected_armies",
    "move_enter_region",
    "route_cost",
    "cost",
    "movement_left",
    "movement_spent",
    "army_movement_left",
    "move_stops_at",
    "move_uncertain_contact",
    "move_route_clear",
    "move_supplied_after",
    "move_unsupplied_after",
    "move_pick_destination",
    "route_review",
    "confirm_move",
    "cancel_move",
    "choose_destination",
    "back_to_map",
    "army_orders",
    "army_people",
    "composition",
    "recovery",
    "next_recovery",
    "last_recovery",
    "recovery_forecast",
    "transfer_formation",
    "transfer",
    "transfer_preserves_movement",
    "transfer_paused_help",
    "people_transfer_help",
    "no_local_people",
    "assigned_site",
    "choose_army",
    "transfer_choose_army",
    "split_new_army",
    "confirm_transfer",
    "formation_slots",
    "empty_formation_slot",
    "person_needs_formation",
    "person_fit",
    "person_wounded",
    "wound_steps_remaining",
    "battle_reports",
    "help_battle",
    "help_battle_reports",
    "help_wounds",
    "battle_recorded",
    "no_battle_reports",
    "older_report",
    "newer_report",
    "battle_outcome",
    "battle_forces",
    "battle_factors",
    "battle_attacker",
    "battle_defender",
    "battle_victory",
    "battle_stalemate",
    "battle_mutual_destruction",
    "battle_annihilation",
    "battle_rout",
    "battle_exchange_limit",
    "battle_exchanges",
    "battle_exhausted",
    "battle_previous_control",
    "battle_structural_damage",
    "battle_occupation",
    "battle_holds_site",
    "battle_withdrew",
    "battle_army_destroyed",
    "battle_counted_elements",
    "battle_slot",
    "battle_combat_losses",
    "battle_encirclement_losses",
    "battle_destroyed",
    "class_officer",
    "person_dead",
    "battle_person_died_wipe",
    "battle_person_no_refuge",
    "battle_wound_wipe",
    "battle_wound_command",
    "battle_assumed_command",
    "battle_previous_commander",
    "battle_person_event",
    "no_battle_people",
    "battle_simultaneous",
    "battle_simultaneous_detail",
    "battle_terrain",
    "battle_defender_resistance",
    "battle_initial_leadership",
    "battle_leadership_change",
    "battle_counter_attack",
    "battle_exchange",
    "battle_attacker_losses",
    "battle_defender_losses",
    "battle_recorded_place",
    "help_leadership",
    "recruit_success",
    "disband_success",
    "armies",
    "own_armies",
    "recruit",
    "disband",
    "gold",
    "wood",
    "stone",
    "troop_warriors",
    "troop_spearmen",
    "troop_archers",
    "troop_riders",
    "troop_medics",
    "troop_siege_engines",
    "empty_slot",
    "no_armies",
    "new_army_help",
    "new_army",
    "army_upkeep",
    "leadership",
    "commander",
    "no_commander",
    "upkeep_deficit",
    "recruit_exhausted",
    "engine_teams",
    "troops",
    "upkeep",
    "recruit_ready",
    "confirm_recruit",
    "disband_warning",
    "disband_people",
    "disband_last",
    "confirm_disband",
    "last_income",
    "upkeep_paid",
    "upkeep_shortfall",
    "help_pan",
    "help_zoom",
    "help_turn",
    "help_menu",
    "help_scope",
    "help_select",
    "help_region",
    "help_navigation",
    "enter_region",
    "select_place",
    "local_control",
    "political_claim",
    "unclaimed",
    "uncontrolled",
    "contested",
    "secure_control",
    "site_supplied",
    "site_unsupplied",
    "supplied_gate",
    "region_sites",
    "anchor_requirements",
    "anchors_help",
    "entrances",
    "connections",
    "gate",
    "anchor",
    "no_connections",
    "credits_title",
    "credits_body",
    "new_title",
    "new_warning",
    "cancel",
    "save_success",
    "load_success",
    "save_failed",
    "load_failed",
    "settings_failed",
    "round",
    "npc_phase",
    "npc_paused",
    "npc_prototype",
    "pause_npcs",
    "resume_npcs",
    "step_npc",
    "load_legacy",
    "legacy_phase",
    "save_player_only",
    "legacy_read_only",
    "save_catalogue",
    "new_save",
    "no_catalogue_saves",
    "previous",
    "next",
    "overwrite",
    "delete",
    "retry_storage",
    "overwrite_warning",
    "save_name_help",
    "confirm_overwrite",
    "create_save",
    "delete_warning",
    "confirm_delete",
    "round_unsaved",
    "round_unsaved_help",
    "retry_save",
    "continue_unsaved",
    "import_campaign",
    "storage_ready",
    "storage_waiting",
    "storage_busy",
    "save_during_orders",
    "manual_save",
    "round_save",
    "imported_save",
    "saved_name",
    "founding_save",
];

impl PresentationData {
    pub fn validate(&self) -> Result<(), String> {
        if self.game_id != "kestrum" || self.start_year == 0 || self.seasons.len() != 4 {
            return Err(
                "Kestrum requires its own save identity, a positive year, and four seasons".into(),
            );
        }
        for key in REQUIRED_TEXT {
            if self
                .text
                .get(*key)
                .is_none_or(|value| value.trim().is_empty())
            {
                return Err(format!("Missing Kestrum interface text: {key}"));
            }
        }
        for label in &self.geography {
            if label.name.trim().is_empty()
                || !label
                    .position
                    .iter()
                    .all(|v| v.is_finite() && (0.0..=1.0).contains(v))
                || !label.size.is_finite()
                || !(12.0..=36.0).contains(&label.size)
            {
                return Err(format!("Invalid geography label: {}", label.name));
            }
        }
        Ok(())
    }

    pub fn text<'a>(&'a self, key: &'a str) -> &'a str {
        self.text.get(key).map(String::as_str).unwrap_or(key)
    }
}
